[[pages]]
path = "index.py"
name = "Home"
icon = ":house:"

[[pages]]
path = "loja1.py"
name = "Cadastro de animais"
icon = ":books:"

[[pages]]
path = "loja2.py"
name = "Memorando"
icon = "ğŸ“–"

[[pages]]
path = "example_app/example_two.py"
name = "Example Two"
icon = "âœï¸"

[[pages]]
path = "example_app/example_three.py"

[[pages]]
path = "example_app/example_five.py"
name = "Example Five"
icon = "ğŸ§°"
