[[pages]]
path = "index.py"
name = "Home"
icon = ":house:"

#[[pages]]
#path = "loja1.py"
#name = "Cadastro dos animais"
#icon = ":books:"

[[pages]]
name = "SANEAR"
icon = ":pig:"
is_section = true

[[pages]]
path = "loja2.py"
name = "Memorando"
icon = "ğŸ“–"

[[pages]]
path = "loja1.py"
name = "Example Two"
icon = "âœï¸"

[[pages]]
name = "Other apps"
icon = ":horse:"
is_section = true

[[pages]]
path = "loja1.py"

[[pages]]
path = "loja1.py"
name = "Example Five"
icon = "ğŸ§°"
in_section = false
